services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - storage:/usr/share/nginx/html/storage:rw
      - ./public:/usr/share/nginx/html/public:rw

  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_horizon
    restart: unless-stopped
    command: php artisan horizon
    environment:
      IS_WORKER: "true"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - storage:/usr/share/nginx/html/storage:rw
      - ./public:/usr/share/nginx/html/public:rw

  nginx:
    image: nginx:1-alpine
    container_name: laravel_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - storage:/usr/share/nginx/html/storage:rw
      - ./public:/usr/share/nginx/html/public:rw
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: spcdb
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql

  redis:
    image: redis:7.2-alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --requirepass redis
    volumes:
      - redis-data:/data

  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_reverb
    restart: always
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    volumes:
      - storage:/usr/share/nginx/html/storage:rw
      - ./public:/usr/share/nginx/html/public:rw

volumes:
  storage:
  db-data:
  redis-data:
